modLoader = "javafml"
loaderVersion = "[34,)"

logoFile = "assets/smoothhud/icon.png"

license = "CC0-1.0"

[[mods]]

modId = "smoothhud"

version = "1.0"

displayName = "SmoothHud"

authors = "treegfx"

description = '''Simple mod to animate the selected hotbar slot highlight when switching slots.'''
[[dependencies.smoothhud]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "BOTH"
